name: Deploy Reusable

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm from the reusable workflow, I can help many other workflows which having repeated tasks"
