name: Node CI Demo

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Run tests
        run: |
          echo "Token from secret: ${{ secrets.SECRET_TOKEN }}"
          npm test
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-node${{ matrix.node-version }}
          path: ./coverage/    # Change as needed
  deploy:
    needs: test
    uses: sandeep1143/Demo_KT/.github/workflows/Deploy/deploy.yml@main
    secrets: inherit
